# Generated by Django 5.1.3 on 2024-11-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_rename_name_course_title_remove_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='internal_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(),
        ),
    ]
