# Generated by Django 5.1.3 on 2024-11-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_course_internal_number_alter_course_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionGrade',
            new_name='ProfGrade',
        ),
    ]
